version: "3.9"
services:
  storage:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: storage
      PGDATA: "/var/lib/postgresql/data/docker-data/storage"
    ports:
      - "5432:5432"
